BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
TARGET_KERNEL_CONFIG := cyanogenmod_deathly_klimtlte_defconfig
TARGET_KERNEL_SOURCE := kernel/samsung/klimtwifi
TARGET_KERNEL_CUSTOM_TOOLCHAIN := arm-eabi-4.8
